"""Qt settings UI for ymt_skirt_01."""

from mgear.core import pyqt as gqt

QtGui, QtCore, QtWidgets, wrapInstance = gqt.qt_import()


class Ui_Form(object):
    def _ring_scale_spin_box(self, parent: QtWidgets.QGroupBox) -> QtWidgets.QDoubleSpinBox:
        spin_box = QtWidgets.QDoubleSpinBox(parent)
        spin_box.setDecimals(3)
        spin_box.setMinimum(0.001)
        spin_box.setMaximum(100.0)
        spin_box.setSingleStep(0.05)
        return spin_box

    def _unit_spin_box(self, parent: QtWidgets.QGroupBox) -> QtWidgets.QDoubleSpinBox:
        spin_box = QtWidgets.QDoubleSpinBox(parent)
        spin_box.setDecimals(2)
        spin_box.setMinimum(0.0)
        spin_box.setMaximum(1.0)
        spin_box.setSingleStep(0.05)
        return spin_box

    def setupUi(self, Form: QtWidgets.QWidget) -> None:
        Form.setObjectName("Form")
        Form.resize(300, 470)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.mainLayout = QtWidgets.QVBoxLayout(self.groupBox)

        self.grid_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.grid_formLayout = QtWidgets.QFormLayout(self.grid_groupBox)
        self.grid_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.leg_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.leg_formLayout = QtWidgets.QFormLayout(self.leg_groupBox)
        self.leg_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.collision_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.collision_formLayout = QtWidgets.QFormLayout(self.collision_groupBox)
        self.collision_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.panels_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.panels_formLayout = QtWidgets.QFormLayout(self.panels_groupBox)
        self.panels_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.rig_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.rig_formLayout = QtWidgets.QFormLayout(self.rig_groupBox)
        self.rig_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)

        self.rows_label = QtWidgets.QLabel(self.grid_groupBox)
        self.rows_spinBox = QtWidgets.QSpinBox(self.grid_groupBox)
        self.rows_spinBox.setMinimum(2)
        self.rows_spinBox.setMaximum(100)
        self.grid_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rows_label)
        self.grid_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rows_spinBox)
        self.cols_label = QtWidgets.QLabel(self.grid_groupBox)
        self.cols_spinBox = QtWidgets.QSpinBox(self.grid_groupBox)
        self.cols_spinBox.setMinimum(3)
        self.cols_spinBox.setMaximum(128)
        self.grid_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cols_label)
        self.grid_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cols_spinBox)
        self.rebuildGrid_pushButton = QtWidgets.QPushButton(self.grid_groupBox)
        self.grid_formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.rebuildGrid_pushButton)
        self.rebuildSpansV_label = QtWidgets.QLabel(self.grid_groupBox)
        self.rebuildSpansV_spinBox = QtWidgets.QSpinBox(self.grid_groupBox)
        self.rebuildSpansV_spinBox.setMinimum(1)
        self.rebuildSpansV_spinBox.setMaximum(256)
        self.grid_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rebuildSpansV_label)
        self.grid_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rebuildSpansV_spinBox)

        self.ringScaleX_label = QtWidgets.QLabel(self.leg_groupBox)
        self.ringScaleX_doubleSpinBox = self._ring_scale_spin_box(self.leg_groupBox)
        self.leg_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ringScaleX_label)
        self.leg_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ringScaleX_doubleSpinBox)
        self.ringScaleZ_label = QtWidgets.QLabel(self.leg_groupBox)
        self.ringScaleZ_doubleSpinBox = self._ring_scale_spin_box(self.leg_groupBox)
        self.leg_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ringScaleZ_label)
        self.leg_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ringScaleZ_doubleSpinBox)
        self.ringScaleY_label = QtWidgets.QLabel(self.leg_groupBox)
        self.ringScaleY_doubleSpinBox = self._ring_scale_spin_box(self.leg_groupBox)
        self.leg_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ringScaleY_label)
        self.leg_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ringScaleY_doubleSpinBox)
        self.ringPositions_label = QtWidgets.QLabel(self.leg_groupBox)
        self.ringPositions_lineEdit = QtWidgets.QLineEdit(self.leg_groupBox)
        self.leg_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ringPositions_label)
        self.leg_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ringPositions_lineEdit)
        self._setup_leg_profile(self.leg_groupBox, self.leg_formLayout)

        self.tightness_label = QtWidgets.QLabel(self.collision_groupBox)
        self.tightness_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.collision_groupBox)
        self.tightness_doubleSpinBox.setDecimals(3)
        self.tightness_doubleSpinBox.setMinimum(0.0)
        self.tightness_doubleSpinBox.setMaximum(1.0)
        self.tightness_doubleSpinBox.setSingleStep(0.05)
        self.collision_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tightness_label)
        self.collision_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tightness_doubleSpinBox)
        self.falloff_label = QtWidgets.QLabel(self.collision_groupBox)
        self.falloff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.collision_groupBox)
        self.falloff_doubleSpinBox.setDecimals(3)
        self.falloff_doubleSpinBox.setMinimum(-1.0)
        self.falloff_doubleSpinBox.setMaximum(1.0)
        self.falloff_doubleSpinBox.setSingleStep(0.05)
        self.collision_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.falloff_label)
        self.collision_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.falloff_doubleSpinBox)
        self.smoothness_label = QtWidgets.QLabel(self.collision_groupBox)
        self.smoothness_doubleSpinBox = self._unit_spin_box(self.collision_groupBox)
        self.collision_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.smoothness_label)
        self.collision_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.smoothness_doubleSpinBox)
        self.follow_label = QtWidgets.QLabel(self.collision_groupBox)
        self.follow_doubleSpinBox = self._unit_spin_box(self.collision_groupBox)
        self.collision_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.follow_label)
        self.collision_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.follow_doubleSpinBox)
        self.followRange_label = QtWidgets.QLabel(self.collision_groupBox)
        self.followRange_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.collision_groupBox)
        self.followRange_doubleSpinBox.setDecimals(4)
        self.followRange_doubleSpinBox.setMinimum(0.0)
        self.followRange_doubleSpinBox.setMaximum(1.0e12)
        self.followRange_doubleSpinBox.setSingleStep(0.01)
        self.collision_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.followRange_label)
        self.collision_formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.followRange_doubleSpinBox)
        self.postCollision_checkBox = QtWidgets.QCheckBox(self.collision_groupBox)
        self.collision_formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.postCollision_checkBox)

        self.seams_label = QtWidgets.QLabel(self.panels_groupBox)
        self.seams_lineEdit = QtWidgets.QLineEdit(self.panels_groupBox)
        self.panels_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.seams_label)
        self.panels_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.seams_lineEdit)
        self.columnFk_checkBox = QtWidgets.QCheckBox(self.panels_groupBox)
        self.panels_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.columnFk_checkBox)

        self.ctlSize_label = QtWidgets.QLabel(self.rig_groupBox)
        self.ctlSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.rig_groupBox)
        self.ctlSize_doubleSpinBox.setDecimals(3)
        self.ctlSize_doubleSpinBox.setMinimum(0.001)
        self.ctlSize_doubleSpinBox.setMaximum(100.0)
        self.ctlSize_doubleSpinBox.setSingleStep(0.1)
        self.rig_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ctlSize_label)
        self.rig_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctlSize_doubleSpinBox)
        self.addJoints_checkBox = QtWidgets.QCheckBox(self.rig_groupBox)
        self.rig_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.addJoints_checkBox)
        self.wave_checkBox = QtWidgets.QCheckBox(self.rig_groupBox)
        self.rig_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wave_checkBox)

        for group_box in (
            self.grid_groupBox,
            self.leg_groupBox,
            self.collision_groupBox,
            self.panels_groupBox,
            self.rig_groupBox,
        ):
            self.mainLayout.addWidget(group_box)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def _setup_leg_profile(self, parent: QtWidgets.QGroupBox, form_layout: QtWidgets.QFormLayout) -> None:
        self.legProfile_groupBox = QtWidgets.QGroupBox(parent)
        layout = QtWidgets.QFormLayout(self.legProfile_groupBox)
        for station in ("thigh", "knee", "calf", "ankle"):
            row = QtWidgets.QHBoxLayout()
            for axis in ("X", "Z"):
                row.addWidget(QtWidgets.QLabel(axis, self.legProfile_groupBox))
                spin_box = self._ring_scale_spin_box(self.legProfile_groupBox)
                spin_box.setMaximum(10000.0)
                setattr(self, station + "Radius" + axis + "_doubleSpinBox", spin_box)
                row.addWidget(spin_box)
            layout.addRow(gqt.fakeTranslate("Form", station.title(), None, -1), row)
        for station in ("thigh", "calf"):
            spin_box = self._unit_spin_box(self.legProfile_groupBox)
            spin_box.setDecimals(4)
            setattr(self, station + "Position_doubleSpinBox", spin_box)
            layout.addRow(gqt.fakeTranslate("Form", station.title() + " Position", None, -1), spin_box)
        self.profileMesh_lineEdit = QtWidgets.QLineEdit(self.legProfile_groupBox)
        layout.addRow(gqt.fakeTranslate("Form", "Body mesh", None, -1), self.profileMesh_lineEdit)
        self.useSelection_pushButton = QtWidgets.QPushButton(self.legProfile_groupBox)
        self.fitProfile_pushButton = QtWidgets.QPushButton(self.legProfile_groupBox)
        layout.addRow(self.useSelection_pushButton)
        layout.addRow(self.fitProfile_pushButton)
        form_layout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.legProfile_groupBox)

    def retranslateUi(self, Form: QtWidgets.QWidget) -> None:
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.groupBox.setTitle("")
        self.grid_groupBox.setTitle(gqt.fakeTranslate("Form", "Grid", None, -1))
        self.leg_groupBox.setTitle(gqt.fakeTranslate("Form", "Leg", None, -1))
        self.collision_groupBox.setTitle(gqt.fakeTranslate("Form", "Collision", None, -1))
        self.panels_groupBox.setTitle(gqt.fakeTranslate("Form", "Panels", None, -1))
        self.rig_groupBox.setTitle(gqt.fakeTranslate("Form", "Rig", None, -1))
        self.rows_label.setText(gqt.fakeTranslate("Form", "Rows", None, -1))
        self.cols_label.setText(gqt.fakeTranslate("Form", "Columns", None, -1))
        self.rebuildGrid_pushButton.setText(gqt.fakeTranslate("Form", "Rebuild Grid Locators", None, -1))
        self.ctlSize_label.setText(gqt.fakeTranslate("Form", "Ctl Size", None, -1))
        self.addJoints_checkBox.setText(gqt.fakeTranslate("Form", "Add Joints", None, -1))
        self.postCollision_checkBox.setText(gqt.fakeTranslate("Form", "Post Collision (2nd pass)", None, -1))
        self.wave_checkBox.setText(gqt.fakeTranslate("Form", "Wave (deterministic oscillator)", None, -1))
        self.rebuildSpansV_label.setText(gqt.fakeTranslate("Form", "Surface Spans V", None, -1))
        self.tightness_label.setText(gqt.fakeTranslate("Form", "Tightness", None, -1))
        self.falloff_label.setText(gqt.fakeTranslate("Form", "Falloff", None, -1))
        self.smoothness_label.setText(gqt.fakeTranslate("Form", "Smoothness", None, -1))
        self.follow_label.setText(gqt.fakeTranslate("Form", "Follow", None, -1))
        self.ringPositions_label.setText(gqt.fakeTranslate("Form", "Ring Positions", None, -1))
        self.seams_label.setText(gqt.fakeTranslate("Form", "Seams", None, -1))
        self.followRange_label.setText(gqt.fakeTranslate("Form", "Follow Range", None, -1))
        self.columnFk_checkBox.setText(gqt.fakeTranslate("Form", "Column FK", None, -1))
        self.ringScaleX_label.setText(gqt.fakeTranslate("Form", "Hip Radius Scale X", None, -1))
        self.ringScaleZ_label.setText(gqt.fakeTranslate("Form", "Hip Radius Scale Z", None, -1))
        self.ringScaleY_label.setText(gqt.fakeTranslate("Form", "Ring Height Scale", None, -1))
        self.legProfile_groupBox.setTitle(gqt.fakeTranslate("Form", "Leg profile", None, -1))
        self.useSelection_pushButton.setText(gqt.fakeTranslate("Form", "Use selection", None, -1))
        self.fitProfile_pushButton.setText(gqt.fakeTranslate("Form", "Fit profile from mesh", None, -1))
